[[GR]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ddeb0edda9dafb800ac4678a13655d995e2aec7c"
os = "windows"

    [[GR.download]]
    sha256 = "2f985d712f3169d1d165edc401fc9f01f75795a6670f46110d92d2208bd3ae2e"
    url = "https://github.com/JuliaBinaryWrappers/GR_jll.jl/releases/download/GR-v0.73.26+0/GR.v0.73.26.i686-w64-mingw32-cxx11.tar.gz"
[[GR]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0b761c166f6d65e7d16e9f908f0e871975c84919"
os = "windows"

    [[GR.download]]
    sha256 = "0ca53c90a8e4648ebe4c7a56fdd422270cc9f68c3c66f398d99dd00ade0b6814"
    url = "https://github.com/JuliaBinaryWrappers/GR_jll.jl/releases/download/GR-v0.73.26+0/GR.v0.73.26.x86_64-w64-mingw32-cxx11.tar.gz"
[[GR]]
arch = "aarch64"
git-tree-sha1 = "2c647ae3b2bbd4dd9da17ace4e635b89dc139f5a"
os = "macos"

    [[GR.download]]
    sha256 = "37461f6d694a7af4dc106281a2671e31588fa28b0e2d2bf223889fbab061183c"
    url = "https://github.com/JuliaBinaryWrappers/GR_jll.jl/releases/download/GR-v0.73.26+0/GR.v0.73.26.aarch64-apple-darwin.tar.gz"
[[GR]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "64bfad8c87e287fa2491169c7f3f37c5ed9760fe"
libc = "glibc"
os = "linux"

    [[GR.download]]
    sha256 = "97d7476b3b59b05c84171aaa918156f5b6981ef3fb712a52c36a0202aeef13c4"
    url = "https://github.com/JuliaBinaryWrappers/GR_jll.jl/releases/download/GR-v0.73.26+0/GR.v0.73.26.aarch64-linux-gnu-cxx11.tar.gz"
[[GR]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4164bf86c7efaff1d296b08e9cea4ebf58fa1743"
libc = "glibc"
os = "linux"

    [[GR.download]]
    sha256 = "b61ff72d13b747e9dc618532cd7d2a080751354ff6f5f9d517017d8eac87841d"
    url = "https://github.com/JuliaBinaryWrappers/GR_jll.jl/releases/download/GR-v0.73.26+0/GR.v0.73.26.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[GR]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b7181129f8fb410ddbde622567afa102e201dcce"
libc = "glibc"
os = "linux"

    [[GR.download]]
    sha256 = "799cc7f85a0480e515cc5d511838ca1867827323bcae90b2bfce02c11cde33e9"
    url = "https://github.com/JuliaBinaryWrappers/GR_jll.jl/releases/download/GR-v0.73.26+0/GR.v0.73.26.i686-linux-gnu-cxx11.tar.gz"
[[GR]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "08bd7525eebc34eb3bb926794cd3f201c621d9af"
libc = "glibc"
os = "linux"

    [[GR.download]]
    sha256 = "194cfd8458361de3ab10456a22ba946fb0447405c10529b8095b2b6066627f3e"
    url = "https://github.com/JuliaBinaryWrappers/GR_jll.jl/releases/download/GR-v0.73.26+0/GR.v0.73.26.powerpc64le-linux-gnu-cxx11.tar.gz"
[[GR]]
arch = "x86_64"
git-tree-sha1 = "b0ac44e02a6ce59d28e2847146f5fde3f0428e20"
os = "macos"

    [[GR.download]]
    sha256 = "54b2e67c41547bbfb71eec9cd440a16245c8abb65f0ccbf5aec0523f282e1b89"
    url = "https://github.com/JuliaBinaryWrappers/GR_jll.jl/releases/download/GR-v0.73.26+0/GR.v0.73.26.x86_64-apple-darwin.tar.gz"
[[GR]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3d40b81fac6f43120cb43982b5fda773bcf44a4b"
libc = "glibc"
os = "linux"

    [[GR.download]]
    sha256 = "87394b2c5dc052b4edbc17d618b8aa4125e8d9d8071d70626f2a21e2155a0e81"
    url = "https://github.com/JuliaBinaryWrappers/GR_jll.jl/releases/download/GR-v0.73.26+0/GR.v0.73.26.x86_64-linux-gnu-cxx11.tar.gz"
[[GR]]
arch = "x86_64"
git-tree-sha1 = "e9ad1cd419734e443bf0a0cf98d043e8a3b32ee0"
os = "freebsd"

    [[GR.download]]
    sha256 = "95a5b246da6a06c2a80458f7554b057a4f58e930b9faf555313425de71d3fc14"
    url = "https://github.com/JuliaBinaryWrappers/GR_jll.jl/releases/download/GR-v0.73.26+0/GR.v0.73.26.x86_64-unknown-freebsd.tar.gz"
