[[GR]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4b66ff9ce2a1d8677bfab02f383140e48b97f4f5"
os = "windows"

    [[GR.download]]
    sha256 = "3f8926adf3cd03c86efb36829cef1e97f0f4ed70fb585ae287879d28286b5f9b"
    url = "https://github.com/JuliaBinaryWrappers/GR_jll.jl/releases/download/GR-v0.73.23+0/GR.v0.73.23.i686-w64-mingw32-cxx11.tar.gz"
[[GR]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4823d3a3de656f6318d5df48e629b93541e26c12"
os = "windows"

    [[GR.download]]
    sha256 = "e4b49c120d9ddf780918ec538eeddfd3c9cb14dab39a2a61f5d72761b02bb453"
    url = "https://github.com/JuliaBinaryWrappers/GR_jll.jl/releases/download/GR-v0.73.23+0/GR.v0.73.23.x86_64-w64-mingw32-cxx11.tar.gz"
[[GR]]
arch = "aarch64"
git-tree-sha1 = "c69c4a7e376598526fbf6f1ab704e7d813d6580e"
os = "macos"

    [[GR.download]]
    sha256 = "84e9aeb312c5d6f9386c647dffe3e381a0b3ed8ae024fca490f9c4a7dd025378"
    url = "https://github.com/JuliaBinaryWrappers/GR_jll.jl/releases/download/GR-v0.73.23+0/GR.v0.73.23.aarch64-apple-darwin.tar.gz"
[[GR]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f2be1334239b2f6cc8ad923672e136335e8ed7cb"
libc = "glibc"
os = "linux"

    [[GR.download]]
    sha256 = "541a2dc465b6166191d05f315b50b9d6595a8571516d4294d51e81cb655a008b"
    url = "https://github.com/JuliaBinaryWrappers/GR_jll.jl/releases/download/GR-v0.73.23+0/GR.v0.73.23.aarch64-linux-gnu-cxx11.tar.gz"
[[GR]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "83ed72a09a3d80b9649f9b6f2c95dadf9f063202"
libc = "glibc"
os = "linux"

    [[GR.download]]
    sha256 = "7947434f0130028a0fa022a247c11954ad5661beb7a092837a5b17ada650d629"
    url = "https://github.com/JuliaBinaryWrappers/GR_jll.jl/releases/download/GR-v0.73.23+0/GR.v0.73.23.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[GR]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7aaf34c8591fceb3c95a1b27fbeba6db8ebd52f5"
libc = "glibc"
os = "linux"

    [[GR.download]]
    sha256 = "0c1078ef3756ab270f2a8991fcc6cf1cdfd8bc756c217a68e93d6ca30af37397"
    url = "https://github.com/JuliaBinaryWrappers/GR_jll.jl/releases/download/GR-v0.73.23+0/GR.v0.73.23.i686-linux-gnu-cxx11.tar.gz"
[[GR]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1f684e353f41b38b1d4a536e89948d440e94e362"
libc = "glibc"
os = "linux"

    [[GR.download]]
    sha256 = "0ba4c5e2cd4b8e4223ca63e6dafab374f12a495124b0c57b1791db8830349f2b"
    url = "https://github.com/JuliaBinaryWrappers/GR_jll.jl/releases/download/GR-v0.73.23+0/GR.v0.73.23.powerpc64le-linux-gnu-cxx11.tar.gz"
[[GR]]
arch = "x86_64"
git-tree-sha1 = "79e07a3bc02c7dcd85513597cef7078dd9db6cfa"
os = "macos"

    [[GR.download]]
    sha256 = "c8ab314a45f37ffb934d44c5deec533f8021a72bf81d0b9dadb0335b202f624c"
    url = "https://github.com/JuliaBinaryWrappers/GR_jll.jl/releases/download/GR-v0.73.23+0/GR.v0.73.23.x86_64-apple-darwin.tar.gz"
[[GR]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7755afb74e2cb1d94b438a52b75ae2b997573a73"
libc = "glibc"
os = "linux"

    [[GR.download]]
    sha256 = "e5d3f6cc5b6c44f0b31d03d189542e995d515c6223c06ed060de75e2b9fe19c1"
    url = "https://github.com/JuliaBinaryWrappers/GR_jll.jl/releases/download/GR-v0.73.23+0/GR.v0.73.23.x86_64-linux-gnu-cxx11.tar.gz"
[[GR]]
arch = "x86_64"
git-tree-sha1 = "7b38870c5781e64d687fe1dfb7622102ac66febb"
os = "freebsd"

    [[GR.download]]
    sha256 = "aad27a0b33bde912cfb42dcd4351ae2eca6b47fda92d8517f7f4a37ae60b99c0"
    url = "https://github.com/JuliaBinaryWrappers/GR_jll.jl/releases/download/GR-v0.73.23+0/GR.v0.73.23.x86_64-unknown-freebsd.tar.gz"
